name: Publish

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  crates-io:
    name: crates.io
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - uses: Swatinem/rust-cache@v2
      - uses: Jimver/cuda-toolkit@master
        with:
          cuda: '13.1.0'
          method: 'network'
          sub-packages: '["nvcc", "cudart", "crt", "thrust", "nvvm", "cublas", "cublas_dev", "cufft", "cufft_dev", "curand", "curand_dev", "nvrtc", "nvrtc_dev"]'
      - uses: ilammy/msvc-dev-cmd@v1
      - run: bun install
      - working-directory: ./ui
        run: bun run build
      - run: cargo publish --workspace --no-verify --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
